name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'dev', 'feature/*' ]
  pull_request:
    branches: [ 'main', 'dev' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      solutionName: Microsoft.Kiota.Http.HttpClientLibrary.sln
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionName }}
      - name: Build
        run: dotnet build ${{ env.solutionName }} --no-restore -c Debug /p:UseSharedCompilation=false
      - name: Test
        run: dotnet test ${{ env.solutionName }} --no-build --verbosity normal -c Debug /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
